# Database configuration for MySQL
server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_auth_role
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# Additional configuration for Hibernate

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

